###
POST  http://localhost:3100/users/
Content-Type: application/json

{   
    "name":"suriya",
    "username":"suriya12345",
    "password": "SIRI@1711",
    "gender": "Male",
    "location":"hyderabad"
}
###
POST  http://localhost:3100/login/
Content-Type: application/json

{   
    "username":"suriya123",
    "password": "SIRI@1711"
}
